name: Container images generator

on:
  push:
    branches-ignore:
      - "dependabot/**"

jobs:
  container-images:
    if: ${{ github.repository_owner == 'konveyor' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build
        run: |
          yarn install
          yarn build
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Push to Quay.io
        uses: elgohr/Publish-Docker-Github-Action@3.02
        with:
          registry: quay.io
          name: konveyor/tackle-ui
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}
          dockerfile: Dockerfile
          snapshot: false
          tags: ${{ steps.extract_branch.outputs.branch }}
          buildoptions: "--pull"
